#! /usr/bin/env bash

# # add app to pythonpath
# export PYTHONPATH="${PWD}":$PYTHONPATH

# Let the DB start
python3 ./app/backend_pre_start.py

# if you are not using alembic, uncomment the next line and comment out the alembic upgrade head
# python3 ./app/db/init_db.py

# Run migrations. Migration scripts can be automatically generated by running
# the following bash command: alembic revision --autogenerate -m "your message"
alembic upgrade head

# Create initial data in DB
python3 ./app/initial_data.py
